[package]
name = "vm"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true
description.workspace = true

[dependencies]
state = { path = "../state" }
tx = { path = "../tx" }
