[package]
name = "tx"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true
description.workspace = true

[dependencies]
state = { path = "../state" } 
bytes = { workspace = true }
